//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kolaysozluk.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("kolaysozluk.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _1200px_Merriam_Webster_logo_svg {
            get {
                object obj = ResourceManager.GetObject("1200px-Merriam-Webster_logo.svg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _1433279304_tureng_sozluk_ico {
            get {
                object obj = ResourceManager.GetObject("1433279304_tureng-sozluk-ico", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap arrow_back_circle {
            get {
                object obj = ResourceManager.GetObject("arrow-back-circle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap arrow_forward_circle {
            get {
                object obj = ResourceManager.GetObject("arrow-forward-circle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to img,
        ///legend {
        /// border:0
        ///}
        ///legend,
        ///td,
        ///th {
        /// padding:0
        ///}
        ///html {
        /// font-family:sans-serif
        ///}
        ///body {
        /// margin:0
        ///}
        ///article,
        ///aside,
        ///details,
        ///figcaption,
        ///figure,
        ///footer,
        ///header,
        ///hgroup,
        ///main,
        ///menu,
        ///nav,
        ///section,
        ///summary {
        /// display:block
        ///}
        ///audio,
        ///canvas,
        ///progress,
        ///video {
        /// display:inline-block;
        /// vertical-align:baseline
        ///}
        ///audio:not([controls]) {
        /// display:none;
        /// height:0
        ///}
        ///[hidden],
        ///template {
        /// display:none
        ///}
        ///a {
        /// background-color:transparent
        ///}
        ///a:active,
        ///a:hover {
        /// outl [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string cambridgecss {
            get {
                return ResourceManager.GetString("cambridgecss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap close_circle {
            get {
                object obj = ResourceManager.GetObject("close-circle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to html {
        /// -webkit-text-size-adjust:100%;
        /// -ms-text-size-adjust:100%
        ///}
        ///body {
        /// margin:0
        ///}
        ///article,
        ///aside,
        ///details,
        ///figcaption,
        ///figure,
        ///footer,
        ///header,
        ///hgroup,
        ///main,
        ///menu,
        ///nav,
        ///section,
        ///summary {
        /// display:block
        ///}
        ///audio,
        ///canvas,
        ///progress,
        ///video {
        /// display:inline-block;
        /// vertical-align:baseline
        ///}
        ///audio:not([controls]) {
        /// display:none;
        /// height:0
        ///}
        ///[hidden],
        ///template {
        /// display:none
        ///}
        ///a {
        /// background-color:transparent
        ///}
        ///a:active,
        ///a:hover {
        /// outline:none
        ///}
        ///abbr[title] {
        ///  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string css {
            get {
                return ResourceManager.GetString("css", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///&lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;tr&quot;&gt;
        ///        &lt;link href=&quot;//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css&quot; rel=&quot;stylesheet&quot; id=&quot;bootstrap-css&quot;&gt;
        ///        &lt;script src=&quot;//netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js&quot;&gt;&lt;/script&gt;
        ///        &lt;!------ Include the above in your HEAD tag ----------&gt;
        ///                    &lt;style type =&quot;text/css&quot;&gt;
        ///            body { background-color: rgb(52, 73, 94);}
        ///            .error-template {padding: 40px 15px;text-align: center;}
        ///            .error-a [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string errorpage {
            get {
                return ResourceManager.GetString("errorpage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @import url(&apos;https://fonts.googleapis.com/css?lang=tr&amp;family=Product+Sans|Roboto:400,700&apos;);
        ///.gb_Ra {
        /// font:13px/27px Roboto,
        /// RobotoDraft,
        /// Arial,
        /// sans-serif;
        /// z-index:986
        ///}
        ///@-moz-keyframes gb__a {
        /// 0% {
        ///  opacity:0
        /// }
        /// 50% {
        ///  opacity:1
        /// }
        ///}
        ///@keyframes gb__a {
        /// 0% {
        ///  opacity:0
        /// }
        /// 50% {
        ///  opacity:1
        /// }
        ///}
        ///a.gb_0 {
        /// border:none;
        /// color:#4285f4;
        /// cursor:default;
        /// font-weight:bold;
        /// outline:none;
        /// position:relative;
        /// text-align:center;
        /// text-decoration:none;
        /// text-transform:up [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string googlecss {
            get {
                return ResourceManager.GetString("googlecss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap kolaysozluk {
            get {
                object obj = ResourceManager.GetObject("kolaysozluk", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap list_circle_outline2 {
            get {
                object obj = ResourceManager.GetObject("list-circle-outline2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap logo_github {
            get {
                object obj = ResourceManager.GetObject("logo-github", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .card-box-title {
        /// color:#375c71;
        /// font-family:&apos;Lato&apos;,Helvetica,Arial,sans-serif;
        /// font-size:1.375em;
        /// letter-spacing:0.0454em;
        /// line-height:1.2272;
        /// position:relative;
        /// z-index:1
        ///}
        ///.card-box-title i {
        /// font-style:normal;
        /// font-variant:small-caps;
        /// font-size:1.047em
        ///}
        ///@media (max-width:47.9375em) {
        /// .card-box-title {
        ///  font-size:1.25em;
        ///  letter-spacing:0.0455em;
        ///  line-height:1.2
        /// }
        ///}
        ///.mw-tooltip .arrow-link:after,
        ///#join-mwu .arrow-link:after,
        ///#social-sidebar-container .mw-tooltip .a [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string merriamcss {
            get {
                return ResourceManager.GetString("merriamcss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap new_logo1 {
            get {
                object obj = ResourceManager.GetObject("new-logo1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap remove_circle {
            get {
                object obj = ResourceManager.GetObject("remove-circle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap search_circle_outline {
            get {
                object obj = ResourceManager.GetObject("search-circle-outline", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///&lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;tr&quot;&gt;
        ///
        ///&lt;style&gt;
        ///    @font-face {
        ///        font-family: octicons-link;
        ///        src: url(data:font/woff;charset=utf-8;base64,d09GRgABAAAAAAZwABAAAAAACFQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABEU0lHAAAGaAAAAAgAAAAIAAAAAUdTVUIAAAZcAAAACgAAAAoAAQAAT1MvMgAAAyQAAABJAAAAYFYEU3RjbWFwAAADcAAAAEUAAACAAJThvmN2dCAAAATkAAAABAAAAAQAAAAAZnBnbQAAA7gAAACyAAABCUM+8IhnYXNwAAAGTAAAABAAAAAQABoAI2dseWYAAAFsAAABPAAAAZwcEq9taGVhZAAAAsgAAAA0AAAANgh4a91oaGVhAAADCAAAABoAAAAkCA8DRGhtdHgAAAL8AAAADAAAAAwGAACfbG9j [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string startup_page {
            get {
                return ResourceManager.GetString("startup_page", resourceCulture);
            }
        }
    }
}
